#!/bin/bash

awk -i inplace -i "utils.awk" -v targetfilepath="${1}" '
BEGIN {
    AVERAGE_WORDS_PER_MINUTE_READ = 230;
}
{
    if ($0 ~ "{{article") {
        len = calculate_article_length();
        sub("{{article ", "{{article |time=" len " ", $0);
    }
    print $0;
}

function calculate_article_length(len) {
    len = run_system_command_with_output("cat " targetfilepath "| wc -w");
    len = int(len / AVERAGE_WORDS_PER_MINUTE_READ);
    if (len <= 0)
        return 1;
    else if (len <= 5)
        return len;
    else {
        len = int((len + 2) / 5);
        return len * 5;
    }
}

function run_system_command_with_output(command,  output) {
    command | getline output;
    close(command);
    return output;
}
' $1
