#!/bin/bash
# @precedes ref

# Parameters:  style = displaystyle, (textstyle)

awk -i inplace -i "utils.awk" -v targetfile="${2}" -v additionalfiles="${3}" '
BEGIN {
    EQ_NUMBER = 0;

    is_reading_equation = 0;
    equation_style   = "";
    equation_content = "";
}
{
    while (1) {
        begin_open_pos = index($0, "{{beginmath");
        end_open_pos   = index($0, "{{endmath");

        ## Example input
        # Apa bepa.
        # CEPA. {{beginmath}}f(x) = \cos(x)\\
        # \tau = 2\pi
        # {{endmath}} cepa depa {{beginmath}}\tau{{endmath}} epa fepa {{beginmath}}
        # a^2 + b^2 = c^2\\
        # c = \sqrt{a^2 + b^2}
        # {{endmath}} gepa.
        # hepa.
        # ipa.

        if (is_reading_equation && end_open_pos == 0) {
            # We are currently reading a multiline equation and this line does not end it.
            # Read one more line of the equation
            equation_content = equation_content $0 "\n";
            break;

        } else if (is_reading_equation && end_open_pos > 0) {
            # We are reading a multiline equation that ends on this line.
            # Read the rest of the equation
            eq = substr($0, 0, end_open_pos - 1);
            equation_content = equation_content eq; 

            # Remove the {{endmath}} from $0
            end_finish_pos = find_template_closing_pos(substr($0, end_open_pos + length(OPENING_BRACKETS))) + length(OPENING_BRACKETS) + end_open_pos + 1;
            math = latex_to_math();
            $0 = math substr($0, end_finish_pos);

            is_reading_equation = 0;
            equation_style   = "";
            equation_content = "";

        } else if (begin_open_pos > 0 && end_open_pos > 0) {
            # We are not currently reading an equation, however,
            # the current line contains both a start and an end of a one-line equation.

            begin_finish_pos = index(substr($0, begin_open_pos), CLOSING_BRACKETS) + begin_open_pos;
            end_finish_pos = find_template_closing_pos(substr($0, end_open_pos + length(OPENING_BRACKETS))) + length(OPENING_BRACKETS) + end_open_pos + 1;

            # Get parameters if any
            template = substr($0, begin_open_pos, begin_finish_pos - begin_open_pos + 1);
            equation_style  = get_parameter(template, "style");

            equation_content = substr($0, begin_finish_pos + 1, end_open_pos - begin_finish_pos - 1);
            math = latex_to_math();

            $0 = substr($0, 0, begin_open_pos - 1) math substr($0, end_finish_pos);

        } else if (begin_open_pos > 0) {
            # We are not currently reading an equation, however,
            # the current line contains a start of a multi-line equation.

            begin_finish_pos = find_template_closing_pos(substr($0, begin_open_pos + length(OPENING_BRACKETS))) + length(OPENING_BRACKETS) + begin_open_pos + 1;

            # Get parameters if any
            template = substr($0, begin_open_pos, begin_finish_pos - begin_open_pos + 1);
            equation_style  = get_parameter(template, "style");

            line = trim(substr($0, 0, begin_open_pos - 1));
            if (line != "")
                print line;

            # Read equation on this line
            equation_content = substr($0, begin_finish_pos) "\n";

            is_reading_equation = 1;
            break;

        } else {
            # We are not reading an equation, and there is not one starting either.
            print $0;
            break;
        }
    }
}

function latex_to_math(eq, tempfile, style, result) {
    tempfile = run_system_command_with_output("mktemp");

    eq = trim(equation_content);
    print eq > tempfile;
    fflush(tempfile);

    style = (equation_style == "textstyle") ? "--inline" : "";
    result = run_system_command_with_output("texmath " style " --from=tex --to=mathml " tempfile);
    run_system_command("rm -f " tempfile);

    EQ_NUMBER += 1;
    return result;
}
' $1
