#!/bin/bash
# @precedes ref

# Parameters:
# * style = displaystyle (default), textstyle
# * newlines = true (default), false

awk -i inplace -i "utils.awk" '
BEGIN {
    EQ_NUMBER = 0

    IS_READING_EQUATION = 0
    NEWLINE_STYLE    = ""
    EQUATION_STYLE   = ""
    EQUATION_CONTENT = ""
}
{
    while (1) {
        begin_open_pos = index($0, "{{beginmath")
        end_open_pos   = index($0, "{{endmath")

        ## Example input
        # Apa bepa.
        # CEPA. {{beginmath}}f(x) = \cos(x)\\
        # \tau = 2\pi
        # {{endmath}} cepa depa {{beginmath}}\tau{{endmath}} epa fepa {{beginmath}}
        # a^2 + b^2 = c^2\\
        # c = \sqrt{a^2 + b^2}
        # {{endmath}} gepa.
        # hepa.
        # ipa.

        if (IS_READING_EQUATION && end_open_pos == 0) {
            # We are currently reading a multiline equation and this line does not end it.
            # Read one more line of the equation
            EQUATION_CONTENT = EQUATION_CONTENT $0 "\n"
            break

        } else if (IS_READING_EQUATION && end_open_pos > 0) {
            # We are reading a multiline equation that ends on this line.
            # Read the rest of the equation
            eq = substr($0, 0, end_open_pos - 1)
            EQUATION_CONTENT = EQUATION_CONTENT eq

            # Remove the {{endmath}} from $0
            end_finish_pos = find_template_closing_pos(substr($0, end_open_pos + length(OPENING_BRACKETS))) + length(OPENING_BRACKETS) + end_open_pos + 1
            math = latex_to_math()
            $0 = math substr($0, end_finish_pos)

            IS_READING_EQUATION = 0
            EQUATION_STYLE   = ""
            EQUATION_CONTENT = ""

        } else if (begin_open_pos > 0 && end_open_pos > 0) {
            # We are not currently reading an equation, however,
            # the current line contains both a start and an end of a one-line equation.

            begin_finish_pos = index(substr($0, begin_open_pos), CLOSING_BRACKETS) + begin_open_pos
            end_finish_pos = find_template_closing_pos(substr($0, end_open_pos + length(OPENING_BRACKETS))) + length(OPENING_BRACKETS) + end_open_pos + 1

            # Get parameters if any
            template = substr($0, begin_open_pos, begin_finish_pos - begin_open_pos + 1)
            EQUATION_STYLE = get_parameter(template, "style")
            NEWLINE_STYLE  = get_parameter(template, "newlines")

            EQUATION_CONTENT = substr($0, begin_finish_pos + 1, end_open_pos - begin_finish_pos - 1)
            math = latex_to_math()

            $0 = substr($0, 0, begin_open_pos - 1) math substr($0, end_finish_pos)

        } else if (begin_open_pos > 0) {
            # We are not currently reading an equation, however,
            # the current line contains a start of a multi-line equation.

            begin_finish_pos = find_template_closing_pos(substr($0, begin_open_pos + length(OPENING_BRACKETS))) + length(OPENING_BRACKETS) + begin_open_pos + 1

            # Get parameters if any
            template = substr($0, begin_open_pos, begin_finish_pos - begin_open_pos + 1)
            EQUATION_STYLE = get_parameter(template, "style")
            NEWLINE_STYLE  = get_parameter(template, "newlines")

            line = trim(substr($0, 0, begin_open_pos - 1))
            if (line != "")
                print line

            # Read equation on this line
            EQUATION_CONTENT = substr($0, begin_finish_pos) "\n"

            IS_READING_EQUATION = 1
            break

        } else {
            # We are not reading an equation, and there is not one starting either.
            print $0
            break
        }
    }
}

function latex_to_math(eq, tempfile, style, result) {
    tempfile = run_system_command_with_output("mktemp")

    eq = trim(EQUATION_CONTENT)
    print eq > tempfile
    fflush(tempfile)

    style = (EQUATION_STYLE == "textstyle") ? "--inline" : ""
    result = run_system_command_with_output("texmath " style " --from=tex --to=mathml " tempfile)
    run_system_command("rm -f " tempfile)

    if (NEWLINE_STYLE == "false") {
        gsub(/\n/, "", result)
    }

    EQ_NUMBER += 1
    return result
}
' "$1"
