#!/bin/bash

awk -i inplace -i "utils.awk" -v targetfile="${2}" -v additionalfiles="${3}" '
BEGIN {
    REF_NO = 0;
}
{
    if ($0 ~ "{{imgframe ") {
        line_read   = "";
        line_unread = $0;
        while (1) {
            open_pos = match(line_unread, "{{imgframe ");
            if (open_pos == 0) {
                line_read = line_read line_unread;
                break;
            }

            template = substr(line_unread, open_pos + length(OPENING_BRACKETS));
            closing_pos = find_template_closing_pos(template);
            template = OPENING_BRACKETS substr(template, 0, closing_pos - 1) CLOSING_BRACKETS;

            ref = get_parameter(template, "ref");
            write_ref(ref);

            file  = get_parameter(template, "file");
            title = get_parameter(template, "title");
            elem  = get_parameter(template, "elem");
            template = "imgframe |num=" REF_NO " |file=" targetfile "-files/" file " |title=" title;
            if (elem != "") {
                elem = targetfile "-files/" elem;
                template = template "|class=fallback ";
                template = template "|elem=<iframe class=\"iframe\" id=\"" ref "\" src=\"" elem "\" scrolling=\"no\" style=\"display:none; border: 0;\"></iframe>";
            } else {
                template = template "|class= |elem=";
            }

            line_read   = line_read substr(line_unread, 0, open_pos - 1) OPENING_BRACKETS template CLOSING_BRACKETS;
            line_unread = substr(line_unread, open_pos + closing_pos + length(CLOSING_BRACKETS) + 1);
        }
        $0 = line_read;
    }
    print $0;
}

function write_ref(ref) {
    REF_NO += 1;
    print ref "=" REF_NO >> additionalfiles "/reflist";
}
' $1
