#!/bin/bash
# @precedes imglinklist, imglinklist_after

awk -i inplace -i "utils.awk" '
BEGIN {
    found_imglinklist = 0;
    should_print_imglinklist_after = 0;
}
{
    if ($0 ~ "{{imglinklist") {
        found_imglinklist = 1;
        print $0;
        next;
    }

    if ($0 ~ "{{imglink ") {
        should_print_imglinklist_after = 1;
        if (found_imglinklist) {
            print adjust_imglink($0);
        } else {
            print "{{imglinklist}}\n" adjust_imglink($0);
            found_imglinklist = 1;
        }
    } else {
        if (should_print_imglinklist_after) {
            should_print_imglinklist_after = 0;
            print "{{imglinklist_after}}\n" $0;
        } else {
            print $0;
        }
        found_imglinklist = 0;
    }
}
ENDFILE {
    if (should_print_imglinklist_after) {
        print "{{imglinklist_after}}";
    }
}

function adjust_imglink(line,  link, img, dir, linkdir) {
    link = get_parameter(line, "link");
    img  = get_parameter(line, "img");
    dir  = get_parameter(line, "dir");
    linkdir = link;
    if (dir != "")
        linkdir = dir "/" link;

    if (link !~ /^http/) {
        if (link !~ /html$/) {
            sub("\\|link *= *" link, "|link=" linkdir ".html", line);
        } else {
            sub("\\|link *= *" link, "|link=" linkdir,         line);
        }
    }
    if (img !~ /^http/)
        sub("\\|img *= *", "|img=" linkdir "-files/", line);
    return line;
}
' "$1"
