#!/bin/bash
# @precedes include-script, include-iframe

awk -i inplace -v targetfile="$2" '
{
    if ($0 ~ "{{include-html") {
        # Add id if not present
        if ($0 !~ "\\|id")
            sub("{{include-html ", "{{include-html |id=" targetfile " ", $0)
        sub("\\|file *= *",        "|file="     targetfile "-files/",    $0)
        sub("\\|fallback *= *",    "|fallback=" targetfile "-files/",    $0)
    }
    print $0
}
' "$1"
