#!/bin/bash
# @precedes thumbnails, thumbnails_after

awk -i inplace -i "utils.awk" -v targetfile="$2" '
BEGIN {
    THUMBNAIL_NO = 0
    FOUND_THUMBNAILS = 0
    SHOULD_PRINT_THUMBNAILS_AFTER = 0
}
{
    if ($0 ~ "{{thumbnails ") {
        FOUND_THUMBNAILS = 1
        print $0
        next
    }

    if ($0 ~ "{{thumbnail ") {
        SHOULD_PRINT_THUMBNAILS_AFTER = 1
        if (FOUND_THUMBNAILS) {
            print add_ordinal_and_target_to_thumbnail($0)
        } else {
            title = get_parameter($0, "title")

            print "{{thumbnails |text=" title "}}\n" add_ordinal_and_target_to_thumbnail($0)
            FOUND_THUMBNAILS = 1
        }
    } else {
        if (SHOULD_PRINT_THUMBNAILS_AFTER) {
            SHOULD_PRINT_THUMBNAILS_AFTER = 0
            print "{{thumbnails_after}}\n" $0
        } else {
            print $0
        }
        FOUND_THUMBNAILS = 0
    }
}
ENDFILE {
    if (SHOULD_PRINT_THUMBNAILS_AFTER) {
        print "{{thumbnails_after}}"
    }
}

function add_ordinal_and_target_to_thumbnail(line) {
    sub("{{thumbnail ", "{{thumbnail |num=" THUMBNAIL_NO " ", line)
    sub("\\|small *= *", "|small=" targetfile "-files/", line)
    sub("\\|large *= *", "|large=" targetfile "-files/", line)

    THUMBNAIL_NO += 1
    return line
}
' "$1"
