#!/bin/bash

awk -i inplace -i "utils.awk" -v targetfile="$2" '
{
    open_pos = index($0, "{{thumbnails_after")
    if (open_pos != 0) {
        template = substr($0, open_pos + length(OPENING_BRACKETS))
        closing_pos = find_template_closing_pos(template)
        template = substr(template, 0, closing_pos - 1 + length(CLOSING_BRACKETS))

        id = get_parameter(template, "id")
        if (id == "") {
            id = targetfile "_0"
        }
        template = "{{thumbnails_after |id=" id "}}"
        $0 = substr($0, 0, open_pos - 1) template substr($0, open_pos + closing_pos + length(CLOSING_BRACKETS) + 1)
    }
    print $0
}
' "$1"
